spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/account
    username: postgres
    password: Qq654321
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false